### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by pocketberserker** [TahaHachana/FSharp-Hub#1]

**Comment by TahaHachana** [comment]
It's a "Fork and knock yourself out" license

**Comment by pocketberserker** [comment]
Thank you for letting me know.
Could you include a license file or write license term on README.md?

https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

**Comment by TahaHachana** [comment]
I'll add the Apache license to the readme.
